name: YAML catalog validation
on:
  push:
    paths: ["data/**", "valid_keys.txt"]
  pull_request:
    paths: ["data/**", "valid_keys.txt"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -vv test.py
